import { db } from "./index";
import { channelPartners } from "./schema";

const main = async () => {
  await db.insert(channelPartners).values([
    // ===================== 12 SCAs =====================
    {
      name: "Andhra Pradesh Scheduled Castes Cooperative Finance Corporation Ltd. (APSCCFC)",
      partnerType: "sca",
      address: "SP River View Apartments, 3rd Floor, Tadepalli, Amaravathi, Andhra Pradesh - 522501",
      latitude: "16.474400",
      longitude: "80.616200",
      npaRatioPercent: "4.20",
    },
    {
      name: "Andhra Pradesh State Financial Corporation (APSFC)",
      partnerType: "sca",
      address: "APSFC Building, Plot OS No.2, 2nd Cross, 3rd Road, Industrial Park, Vijayawada, Andhra Pradesh - 520007",
      latitude: "16.506200",
      longitude: "80.648000",
      npaRatioPercent: "5.10",
    },
    {
      name: "Assam State Development Corporation for SCs Ltd. (ASCDC)",
      partnerType: "sca",
      address: "Swahid Dilip Hozori Path, Sarumotoria, Dispur, Guwahati, Assam - 781006",
      latitude: "26.144500",
      longitude: "91.736200",
      npaRatioPercent: "6.80",
    },
    {
      name: "Bihar State SCs Co-operative Development Corporation Ltd. (BSSCCDC)",
      partnerType: "sca",
      address: "RN-212, Officers Colony (Block-A), Bailey Road, Patna, Bihar - 800001",
      latitude: "25.594100",
      longitude: "85.137600",
      npaRatioPercent: "7.30",
    },
    {
      name: "Chandigarh SCs, BCs & Minorities Financial & Development Corporation Ltd. (CSCFDC)",
      partnerType: "sca",
      address: "3rd Floor, Additional Town Hall Building, Sector-17-C, Chandigarh - 160017",
      latitude: "30.733300",
      longitude: "76.779400",
      npaRatioPercent: "3.90",
    },
    {
      name: "Chhatisgarh State Antavasayee Sahkari Fin. & Dev. Corpn. (CGSCFDC)",
      partnerType: "sca",
      address: "4th Floor, Business Complex, Chhattisgarh Housing Board Bhawan, Naya Raipur, Chhattisgarh - 492101",
      latitude: "21.170200",
      longitude: "81.882500",
      npaRatioPercent: "5.50",
    },
    {
      name: "Dadra & Nagar Haveli, Daman & Diu SCs/STs/OBCs & Minorities Financial & Development Corporation (DNDSFDC)",
      partnerType: "sca",
      address: "Ground Floor, Right Wing, New Collectorate Building, Near Electricity Department, Opp. 66 KVA Sub-Station, 66 KVA Road, Silvassa, Dadra & Nagar Haveli, Daman & Diu - 396230",
      latitude: "20.273800",
      longitude: "73.016900",
      npaRatioPercent: "4.60",
    },
    {
      name: "Delhi SC/ST/OBC/Minorities & Handicapped Financial & Development Corporation (DSFDC)",
      partnerType: "sca",
      address: "Ambedkar Bhawan, Sector-16, Opp. Sector-11, Rohini, Delhi - 110085",
      latitude: "28.749500",
      longitude: "77.056500",
      npaRatioPercent: "6.10",
    },
    {
      name: "Gujarat SCs Development Corporation (GSCDC)",
      partnerType: "sca",
      address: "Dr Jivraj Mehta Bhawan, Block-10, II Floor, Old Sachivalaya, Gandhinagar, Gujarat - 382010",
      latitude: "23.215600",
      longitude: "72.636900",
      npaRatioPercent: "3.40",
    },
    {
      name: "Dr. Ambedkar Antyodaya Vikas Nigam (S.C.) (DAAVN)",
      partnerType: "sca",
      address: "Karmayogi Bhavan, Block No.2, D-2 Wing, 4th Floor, Sector-10/B, Gandhinagar, Gujarat",
      latitude: "23.215600",
      longitude: "72.636900",
      npaRatioPercent: "5.90",
    },
    {
      name: "Goa State SCs & OBCs Finance and Development Corporation Ltd. (GSCOBCDC)",
      partnerType: "sca",
      address: "4th Floor, Patto Centre, Near K.T.C. Bus Stand, Panaji, Goa - 403001",
      latitude: "15.490900",
      longitude: "73.827800",
      npaRatioPercent: "4.00",
    },
    {
      name: "Haryana SCs Fin. and Development Corporation Ltd. (HSCDC)",
      partnerType: "sca",
      address: "SCO-2427-28, Sector 22-C, Chandigarh - 160022",
      latitude: "30.733300",
      longitude: "76.779400",
      npaRatioPercent: "6.50",
    },

    // ===================== 11 PSBs =====================
    {
      name: "Indian Overseas Bank",
      partnerType: "psb",
      address: "Central Office, 763, Anna Salai, Chennai, Tamil Nadu - 600002",
      latitude: "13.082700",
      longitude: "80.270700",
      npaRatioPercent: "8.20",
    },
    {
      name: "Bank of Baroda",
      partnerType: "psb",
      address: "Baroda Bhavan, 7th Floor, R.C. Dutt Road, Vadodara, Gujarat - 390007",
      latitude: "22.307200",
      longitude: "73.181200",
      npaRatioPercent: "3.10",
    },
    {
      name: "Canara Bank",
      partnerType: "psb",
      address: "Head Office, 112, J.C. Road, Bengaluru, Karnataka - 560002",
      latitude: "12.971600",
      longitude: "77.594600",
      npaRatioPercent: "4.50",
    },
    {
      name: "Punjab National Bank",
      partnerType: "psb",
      address: "Plot No. 4, Sector 10, Dwarka, New Delhi - 110075",
      latitude: "28.589500",
      longitude: "77.041000",
      npaRatioPercent: "5.80",
    },
    {
      name: "Punjab & Sind Bank",
      partnerType: "psb",
      address: "Priority Sector Advance Department, 5th Floor, 21 Rajendra Place, New Delhi - 110008",
      latitude: "28.641700",
      longitude: "77.175000",
      npaRatioPercent: "7.90",
    },
    {
      name: "Union Bank of India",
      partnerType: "psb",
      address: "Rural & Agri Business Department, Central Office, Union Bank Bhavan, Nariman Point, Mumbai, Maharashtra - 400021",
      latitude: "18.925600",
      longitude: "72.824200",
      npaRatioPercent: "4.90",
    },
    {
      name: "Indian Bank",
      partnerType: "psb",
      address: "Corporate Office, No.254-260, Avvai Shanmugam Salai, Gowdia Mutt Road, Royapettah, Chennai, Tamil Nadu - 600014",
      latitude: "13.056900",
      longitude: "80.263600",
      npaRatioPercent: "3.70",
    },
    {
      name: "Bank of Maharashtra",
      partnerType: "psb",
      address: "Head Office, Lokmangal, 1501, Shivajinagar, Pune, Maharashtra - 411005",
      latitude: "18.520400",
      longitude: "73.856700",
      npaRatioPercent: "5.20",
    },
    {
      name: "Bank of India",
      partnerType: "psb",
      address: "Bandra Kurla Complex, Bandra (East), Mumbai, Maharashtra - 400051",
      latitude: "19.066200",
      longitude: "72.868600",
      npaRatioPercent: "6.30",
    },
    {
      name: "Central Bank of India",
      partnerType: "psb",
      address: "Chandermukhi Building, Nariman Point, Mumbai, Maharashtra - 400021",
      latitude: "18.925600",
      longitude: "72.824200",
      npaRatioPercent: "9.10",
    },
    {
      name: "UCO Bank",
      partnerType: "psb",
      address: "No. 3 & 4, DD Block, Sector-1, Bidhannagar, Kolkata, West Bengal - 700064",
      latitude: "22.585200",
      longitude: "88.416200",
      npaRatioPercent: "4.40",
    },

    // ===================== 7 NBFC-MFIs =====================
    {
      name: "Anik Financial Services Private Limited",
      partnerType: "nbfc_mfi",
      address: "Regd. Office: Sahyadri Building, Behind Amitesh Hotel, Ambajogai Road, Sai Naka, Latur, Maharashtra - 413512",
      latitude: "18.408800",
      longitude: "76.560400",
      npaRatioPercent: "18.40",
      status: "suspended_high_npa",
    },
    {
      name: "Grameen Development & Finance Private Limited",
      partnerType: "nbfc_mfi",
      address: "Dubjent, Kulshi Road, Chhaygaon, Kamrup, Assam - 781124",
      latitude: "26.100000",
      longitude: "91.400000",
      npaRatioPercent: "8.60",
    },
    {
      name: "ASA International Microfinance Ltd.",
      partnerType: "nbfc_mfi",
      address: "Victoria Park, 4th Floor, GN-37/2, Sector-V, Salt Lake City, Kolkata, West Bengal - 700091",
      latitude: "22.576000",
      longitude: "88.434800",
      npaRatioPercent: "6.90",
    },
    {
      name: "Midland Microfin Ltd.",
      partnerType: "nbfc_mfi",
      address: "The Axis, Plot No.1, R.B. Badri Dass Colony, BMC Chowk, G.T. Road, Jalandhar, Punjab - 144001",
      latitude: "31.326000",
      longitude: "75.576200",
      npaRatioPercent: "9.80",
    },
    {
      name: "Satin Creditcare Network Ltd.",
      partnerType: "nbfc_mfi",
      address: "Plot No.492, Udyog Vihar, Phase-III, Gurugram, Haryana - 122016",
      latitude: "28.459500",
      longitude: "77.026600",
      npaRatioPercent: "7.20",
    },
    {
      name: "Pahal Financial Services Pvt. Ltd.",
      partnerType: "nbfc_mfi",
      address: "7th Floor, Binori B Square-2, Opp. Hathising Ni Vadi, Ambli-Iscon Road, Ahmedabad, Gujarat - 380054",
      latitude: "23.022500",
      longitude: "72.571400",
      npaRatioPercent: "5.40",
    },
    {
      name: "Vector Finance PVT LTD",
      partnerType: "nbfc_mfi",
      address: "RO-K7/110, Ground Floor, Klinga Vihar, P.S. Khandagiri, Bhubaneswar, Odisha - 751029",
      latitude: "20.296100",
      longitude: "85.824500",
      npaRatioPercent: "21.70",
      status: "suspended_high_npa",
    },
  ]);

  console.log("Channel partners seed completed");
  process.exit(0);
};

main().catch((error) => {
  console.error("Channel partners seed failed:", error);
  process.exit(1);
});